Vagrant.configure("2") do |config|
  nodes = [
    { name: "node-1", ip: "192.168.100.11" },
    { name: "node-2", ip: "192.168.100.12" },
    { name: "node-3", ip: "192.168.100.13" }
  ]

  config.vm.box = "generic/ubuntu2204"
  config.vm.box_check_update = false

  nodes.each do |node|
    config.vm.define node[:name] do |n|
      n.vm.hostname = node[:name]
      n.vm.network "private_network",
                   ip: node[:ip],
                   libvirt__network_name: "vagrant-private",
                   libvirt__dhcp_enabled: false

      n.vm.provider :libvirt do |v|
        v.memory = 32768
        v.cpus = 10
      end

      # Esta se ejecuta automáticamente al hacer `vagrant up`
      n.vm.provision "basic", type: "shell", path: "scripts/basic-deploy.sh"

      # Estas solo se ejecutan si las invocás manualmente con --provision-with
      if node[:name] == "node-1"
        # Provision
        n.vm.provision "master", type: "shell", path: "scripts/master-deploy.sh", run: "never"
        n.vm.provision "dashboard", type: "shell", path: "scripts/dashboard.sh", run: "never"
        n.vm.provision "kubevirt", type: "shell", path: "scripts/kubevirt.sh", run: "never"
        n.vm.provision "metrics-server", type: "shell", path: "scripts/metrics-server.sh", run: "never"
        n.vm.provision "pre-process", type: "shell", path: "scripts/preprocess.sh", run: "never"
        n.vm.provision "project", type: "shell", path: "scripts/project.sh", run: "never"
        n.vm.provision "post-process", type: "shell", path: "scripts/postprocess.sh", run: "never"
        n.vm.provision "token", type: "shell", path: "scripts/create-token.sh", run: "never"
      else
        n.vm.provision "worker", type: "shell", path: "scripts/worker-deploy.sh", run: "never"
      end
    end
  end
end

