apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-storage
  namespace: datadriven
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-provisioning
  namespace: datadriven
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

