apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ubuntu22-factoryfloor
  namespace: factory-floor
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: ubuntu22-factoryfloor
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
        resources:
          requests:
            memory: 1Gi
            cpu: "2"
      networks:
        - name: default
          pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/containerdisks/ubuntu:22.04
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              disable_root: true
              ssh_pwauth: true
              users:
                - name: jorge
                  groups: sudo
                  shell: /bin/bash
                  sudo: ['ALL=(ALL) NOPASSWD:ALL']
                  lock_passwd: false
                  passwd: $6$EtaUTWh/HshzprTY$7jmKjmkCCbyR4qVy9D6/dVtis7C8XN.b4oi5TsPYZJEn8qn/bTrgZBSt/Nwu8wvtHAEjxPOB410VXqR3uMG/r/
              runcmd:
                - echo "VM lista" > /home/jorge/listo.txt
