apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: ubuntu22-dv
  namespace: factory-floor
spec:
  source:
    http:
      url: http://10.0.0.104:5000/download/ubuntu22.04-mininet-wifi.img
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
    storageClassName: local-path
