apiVersion: v1
kind: Service
metadata:
  name: ryu
  namespace: datadriven
spec:
  type: LoadBalancer
  selector:
    app: ryu
  ports:
    - name: http
      port: 6633
      targetPort: 6633
      nodePort: 30633
