apiVersion: v1
kind: Service
metadata:
  name: bentoml
  namespace: datadriven
spec:
  type: LoadBalancer
  selector:
    app: bentoml
  ports:
    - name: http
      port: 3001
      targetPort: 3001
      nodePort: 30031
