apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: datadriven
spec:
  selector:
    app: influxdb
  type: LoadBalancer
  ports:
    - name: http
      port: 8086
      targetPort: 8086

